// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Cast here because defineConfig expects a string, and we rely on DATABASE_URL
    // being defined in the environment for any place this config runs (local, CI, Vercel).
    url: process.env["DATABASE_URL"] as string,
  },
});
