/**
 * Seed data for VehicleEntryRequirement table.
 * 
 * This contains curated TIP (Temporary Import Permit) and Carnet de Passages
 * requirements for common overland motorcycle travel destinations.
 * 
 * Sources:
 * - Official government websites (Banjercito, SENASA, etc.)
 * - Overland Association (carnet requirements)
 * - ADVRider forums and trip reports
 * - ItchyBoots, Mad or Nomad, and other moto travel resources
 * 
 * Last updated: March 2026
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Common documents required for most TIPs
const STANDARD_TIP_DOCS = [
  "Valid passport",
  "Original vehicle title",
  "Vehicle registration",
  "Driver's license",
  "Proof of insurance",
];

const vehicleRequirements = [
  // ============================================
  // NORTH AMERICA
  // ============================================
  {
    destCountry: "MX",
    countryName: "Mexico",
    tipRequired: true,
    tipCostUsd: 55,
    tipValidityDays: 180,
    tipObtainAt: "online",
    tipAgency: "Banjercito",
    tipUrl: "https://www.banjercito.com.mx/registroVehiculos/",
    tipDocuments: [
      ...STANDARD_TIP_DOCS,
      "Credit card for deposit (Visa/Mastercard)",
      "FMM tourist permit",
    ],
    tipNotes: "Apply online 7-60 days before entry. Deposit varies by vehicle age ($200-$400 USD). TIP not required for Baja California peninsula or border zone (within 25km of border). Must cancel TIP when leaving Mexico or forfeit deposit and face future entry issues.",
    tipProcessingDays: 3,
    carnetRequired: false,
    carnetAccepted: false,
    depositRequired: true,
    depositAmountUsd: 300,
    depositRefundable: true,
    depositNotes: "Refunded to credit card when TIP is properly cancelled at border. Process takes 4-6 weeks.",
    insuranceRequired: true,
    insuranceNotes: "Mexican liability insurance mandatory. US/Canadian policies not valid. Purchase at border or online (Sanborn's, MexPro, Baja Bound). ~$15-30/day or $200-400/year.",
    sourceUrl: "https://www.banjercito.com.mx/",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "US",
    countryName: "United States",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 365,
    tipObtainAt: "border",
    tipAgency: "CBP (Customs and Border Protection)",
    tipUrl: "https://www.cbp.gov/travel/international-visitors/temporary-importation-vehicles",
    tipDocuments: [
      "Valid passport",
      "Vehicle registration",
      "Proof of ownership (title)",
      "Valid driver's license",
    ],
    tipNotes: "Non-residents may temporarily import a motorcycle for up to one year. Must be for personal use only, not for sale. EPA exemption may be required for non-US-spec vehicles older than 21 years.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Liability insurance required in most states. International policies may be accepted; verify with your insurer.",
    sourceUrl: "https://www.cbp.gov/",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "CA",
    countryName: "Canada",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 365,
    tipObtainAt: "border",
    tipAgency: "CBSA (Canada Border Services Agency)",
    tipUrl: "https://www.cbsa-asfc.gc.ca/travel-voyage/tpv-vpv-eng.html",
    tipDocuments: [
      "Valid passport",
      "Vehicle registration",
      "Proof of ownership",
      "Driver's license",
    ],
    tipNotes: "Temporary import for up to 12 months for personal use. Vehicle must leave with owner. No duty or taxes if temporary.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Provincial minimum liability insurance required. Most US policies extend to Canada; verify coverage.",
    sourceUrl: "https://www.cbsa-asfc.gc.ca/",
    lastVerified: new Date("2026-03-01"),
  },

  // ============================================
  // CENTRAL AMERICA
  // ============================================
  {
    destCountry: "BZ",
    countryName: "Belize",
    tipRequired: true,
    tipCostUsd: 50,
    tipValidityDays: 30,
    tipObtainAt: "border",
    tipAgency: "Belize Customs",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "TIP valid for 30 days, can extend at customs office. Fumigation fee may apply (~$5). Border crossings at Chetumal (Mexico) and Melchor de Mencos (Guatemala).",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Belizean insurance required. Can purchase at border. ~$15-20/week.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "GT",
    countryName: "Guatemala",
    tipRequired: true,
    tipCostUsd: 40,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "SAT (Superintendencia de Administración Tributaria)",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "TIP valid for 90 days within CA-4 region (Guatemala, Honduras, El Salvador, Nicaragua). Single TIP covers all four countries. Can extend once for additional 90 days.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Guatemalan insurance required. Purchase at border or from agencies in Antigua. ~$20-30/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "HN",
    countryName: "Honduras",
    tipRequired: true,
    tipCostUsd: 35,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Aduana Honduras",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Part of CA-4 agreement. If entering from another CA-4 country with valid TIP, no new permit needed. 90 days total in CA-4 region. El Amatillo and Agua Caliente are common crossings.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Honduran insurance required. Can purchase at border. ~$15-25/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "SV",
    countryName: "El Salvador",
    tipRequired: true,
    tipCostUsd: 30,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Aduana El Salvador",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Part of CA-4 agreement. WARNING: Not all border crossings have customs offices. La Hachadura (from Guatemala) and El Amatillo (from Honduras) are recommended. Verify customs presence before crossing.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Salvadoran insurance required. Purchase at border. ~$15-20/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "NI",
    countryName: "Nicaragua",
    tipRequired: true,
    tipCostUsd: 35,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "DGA (Dirección General de Aduanas)",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Part of CA-4 agreement. Las Manos and El Espino are common crossings from Honduras. Peñas Blancas from Costa Rica. Border fees vary, expect $12-15 in various charges.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Nicaraguan insurance required. Purchase at border. ~$12-20/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "CR",
    countryName: "Costa Rica",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Ministerio de Hacienda",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "No TIP fee but must obtain permit at customs. Valid for 90 days, extensions difficult. Peñas Blancas (Nicaragua border) and Paso Canoas (Panama border). Vehicle cannot stay without owner - must exit together.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Costa Rican insurance (SOA) mandatory. Purchase at border from INS agents. ~$15-30/month. Must have valid policy to get TIP.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "PA",
    countryName: "Panama",
    tipRequired: true,
    tipCostUsd: 20,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Autoridad Nacional de Aduanas",
    tipDocuments: [...STANDARD_TIP_DOCS, "Police clearance may be requested"],
    tipNotes: "TIP valid for 90 days. Paso Canoas is the only crossing from Costa Rica. NO ROAD CONNECTION to Colombia - must ship motorcycle (ferry from Panama City or Cartagena, or container). Darien Gap is impassable.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Panamanian insurance required. Purchase at border or Panama City. ~$20-40/month.",
    lastVerified: new Date("2026-03-01"),
  },

  // ============================================
  // SOUTH AMERICA
  // ============================================
  {
    destCountry: "CO",
    countryName: "Colombia",
    tipRequired: true,
    tipCostUsd: 50,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "DIAN (Dirección de Impuestos y Aduanas Nacionales)",
    tipUrl: "https://www.dian.gov.co/",
    tipDocuments: [...STANDARD_TIP_DOCS, "SIVIVIR online form (required before arrival)"],
    tipNotes: "Must complete SIVIVIR form online before arrival. TIP valid for 90 days, can extend. Arriving by ship from Panama: Cartagena or Turbo ports. Vehicle must be fumigated. Process can take 1-3 days in port.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "SOAT insurance mandatory. Purchase in any town. ~$50-100/year for motorcycle.",
    sourceUrl: "https://www.dian.gov.co/",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "EC",
    countryName: "Ecuador",
    tipRequired: true,
    tipCostUsd: 45,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "SENAE (Servicio Nacional de Aduana del Ecuador)",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "TIP valid for 90 days, extensions available at SENAE offices. Rumichaca and Tulcán from Colombia; Huaquillas and Macará from Peru. Vehicle exit must be same border as entry.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "SPPAT insurance required. Purchase at border or in cities. ~$5-15/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "PE",
    countryName: "Peru",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "SUNAT",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP valid for 90 days. Can extend at SUNAT offices in major cities. Aguas Verdes/Huaquillas from Ecuador; Desaguadero and Yunguyo from Bolivia; Tacna from Chile. Keep TIP paperwork safe - needed for exit.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "SOAT insurance mandatory. Purchase at border or any town. ~$20-40/3 months.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "BO",
    countryName: "Bolivia",
    tipRequired: true,
    tipCostUsd: 55,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Aduana Nacional de Bolivia",
    tipDocuments: [...STANDARD_TIP_DOCS, "Copies of all documents"],
    tipNotes: "TIP valid for 90 days. Extensions at Aduana offices. Desaguadero from Peru is most common crossing. Bring multiple copies of all documents. Border officials may request 'fees' - politely ask for official receipt.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "SOAT mandatory. Purchase at border or La Paz. ~$20-30/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "CL",
    countryName: "Chile",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "SAG and Aduana",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP valid for 90 days. SAG agricultural inspection required (no fresh food). Multiple crossings from Argentina. Chungará from Bolivia. Note: Some crossings closed in winter. Carretera Austral requires ferry segments.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "SOAP insurance mandatory. Purchase at border or any town. ~$10-20/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "AR",
    countryName: "Argentina",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "AFIP/Aduana",
    tipDocuments: [
      ...STANDARD_TIP_DOCS,
      "Título or Cédula Verde if Argentine-registered vehicle",
    ],
    tipNotes: "Free TIP valid for 90 days (8 months for own vehicle). Many crossings from Chile, Bolivia, Paraguay, Brazil, Uruguay. Efficient border procedures. Vehicle can stay without owner up to 8 months total per year.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Mercosur insurance (Carta Verde) valid if from member country. Otherwise purchase Argentine policy at border. ~$30-50/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "BR",
    countryName: "Brazil",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Receita Federal",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP valid for 90 days. Extensions at Receita Federal offices. Many crossings from Argentina, Paraguay, Uruguay. Foz do Iguaçu is popular. TIP is called DIAT (Declaração de Importação de Admissão Temporária).",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Carta Verde (Mercosur green card) from member countries accepted. Otherwise purchase local DPVAT. ~$30-60/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "UY",
    countryName: "Uruguay",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Dirección Nacional de Aduanas",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP valid for 90 days. Easy borders from Argentina (Colonia, Paysandú) and Brazil. Efficient processing.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Carta Verde from Mercosur countries accepted. Otherwise local SOA required. ~$25-40/month.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "PY",
    countryName: "Paraguay",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Dirección Nacional de Aduanas",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP valid for 90 days. Ciudad del Este from Brazil (busy crossing). Encarnación from Argentina. Simple process.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Carta Verde from Mercosur accepted. Local insurance ~$15-25/month.",
    lastVerified: new Date("2026-03-01"),
  },

  // ============================================
  // CARNET REQUIRED COUNTRIES (Africa, Middle East, Asia)
  // ============================================
  {
    destCountry: "IN",
    countryName: "India",
    tipRequired: false,
    carnetRequired: true,
    carnetAccepted: true,
    carnetIssuers: [
      { country: "US", org: "ATA Carnet (USCIB)", url: "https://www.atacarnet.com/" },
      { country: "GB", org: "RAC", url: "https://www.rac.co.uk/drive/advice/carnet-de-passages/" },
      { country: "DE", org: "ADAC", url: "https://www.adac.de/" },
      { country: "AU", org: "AAA", url: "https://www.aaa.asn.au/" },
    ],
    carnetNotes: "Carnet de Passages mandatory. High deposit required (often 300-800% of vehicle value). Apply through your home country's automobile association 4-8 weeks in advance.",
    carnetProcessingWeeks: 6,
    depositRequired: true,
    depositAmountUsd: null, // Varies by vehicle value
    depositNotes: "Deposit or bank guarantee typically 300-800% of vehicle value. Refunded when carnet returned with all pages stamped.",
    insuranceRequired: true,
    insuranceNotes: "Indian insurance required. Can arrange in advance or purchase in Delhi/Mumbai.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "PK",
    countryName: "Pakistan",
    tipRequired: false,
    carnetRequired: true,
    carnetAccepted: true,
    carnetIssuers: [
      { country: "US", org: "ATA Carnet (USCIB)", url: "https://www.atacarnet.com/" },
      { country: "GB", org: "RAC", url: "https://www.rac.co.uk/drive/advice/carnet-de-passages/" },
    ],
    carnetNotes: "Carnet de Passages required. Border crossings with India limited (Wagah). Crossings from Iran and China available.",
    carnetProcessingWeeks: 6,
    depositRequired: true,
    insuranceRequired: true,
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "EG",
    countryName: "Egypt",
    tipRequired: false,
    carnetRequired: true,
    carnetAccepted: true,
    carnetIssuers: [
      { country: "US", org: "ATA Carnet (USCIB)", url: "https://www.atacarnet.com/" },
      { country: "GB", org: "RAC", url: "https://www.rac.co.uk/drive/advice/carnet-de-passages/" },
    ],
    carnetNotes: "Carnet de Passages required. Common entry via ferry from Jordan (Aqaba to Nuweiba) or overland from Libya/Sudan.",
    carnetProcessingWeeks: 6,
    depositRequired: true,
    insuranceRequired: true,
    insuranceNotes: "Egyptian insurance required. Can purchase at border or in Cairo.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "KE",
    countryName: "Kenya",
    tipRequired: false,
    carnetRequired: true,
    carnetAccepted: true,
    carnetIssuers: [
      { country: "US", org: "ATA Carnet (USCIB)", url: "https://www.atacarnet.com/" },
      { country: "GB", org: "RAC", url: "https://www.rac.co.uk/drive/advice/carnet-de-passages/" },
      { country: "ZA", org: "AA South Africa", url: "https://www.aa.co.za/" },
    ],
    carnetNotes: "Carnet de Passages required. Popular overland route from Ethiopia or Tanzania. Nairobi is a good base for vehicle services.",
    carnetProcessingWeeks: 6,
    depositRequired: true,
    insuranceRequired: true,
    insuranceNotes: "COMESA Yellow Card insurance covers multiple East/Southern African countries. Purchase in Nairobi.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "ZA",
    countryName: "South Africa",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 365,
    tipObtainAt: "border",
    tipAgency: "SARS (South African Revenue Service)",
    tipDocuments: [...STANDARD_TIP_DOCS, "Police clearance for vehicle"],
    tipNotes: "Carnet NOT required but accepted. TIP available at border for up to 12 months. Popular end point for Cape Town to Cairo route.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "South African insurance required. Many providers in major cities.",
    lastVerified: new Date("2026-03-01"),
  },

  // ============================================
  // EUROPE (Schengen and non-Schengen)
  // ============================================
  {
    destCountry: "GB",
    countryName: "United Kingdom",
    tipRequired: false,
    carnetRequired: false,
    carnetAccepted: true,
    tipNotes: "No TIP required for temporary visitors. Vehicle can stay up to 12 months. Entry via ferry from France, Netherlands, Belgium, Spain, or Ireland.",
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "UK motor insurance required. EU Green Card system still applies. Most EU policies extend coverage.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "TR",
    countryName: "Turkey",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 180,
    tipObtainAt: "border",
    tipAgency: "Turkish Customs",
    tipDocuments: [...STANDARD_TIP_DOCS, "Green Card or Turkish insurance"],
    tipNotes: "Free TIP valid for 180 days. Vehicle details entered in passport - must exit with same vehicle. Key transit country between Europe and Asia.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Green Card accepted from most European countries. Otherwise purchase Turkish policy at border.",
    lastVerified: new Date("2026-03-01"),
  },
  {
    destCountry: "MA",
    countryName: "Morocco",
    tipRequired: true,
    tipCostUsd: 0,
    tipValidityDays: 90,
    tipObtainAt: "border",
    tipAgency: "Douane Marocaine",
    tipDocuments: STANDARD_TIP_DOCS,
    tipNotes: "Free TIP (D16ter form) valid for 90 days. Ferry from Spain (Tarifa, Algeciras) to Tangier. Popular motorcycle destination. Extensions at customs offices.",
    carnetRequired: false,
    carnetAccepted: true,
    depositRequired: false,
    insuranceRequired: true,
    insuranceNotes: "Moroccan insurance required. Green Card from some EU countries accepted. Otherwise purchase at port/border. ~$30-50/month.",
    lastVerified: new Date("2026-03-01"),
  },
];

export async function seedVehicleEntryRequirements() {
  console.log("Seeding vehicle entry requirements...");

  for (const req of vehicleRequirements) {
    await prisma.vehicleEntryRequirement.upsert({
      where: { destCountry: req.destCountry },
      update: req,
      create: req,
    });
    console.log(`  ✓ ${req.countryName} (${req.destCountry})`);
  }

  console.log(`\nSeeded ${vehicleRequirements.length} vehicle entry requirements.`);
}

// Allow running directly
if (require.main === module) {
  seedVehicleEntryRequirements()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}
